### ISSUE TITLE
npm run build throws error

### ISSUE THREAD

**Issue by phdowling** [PokemonGoers/PokeData#122]
See here:

``` bash
Philipps-Air:PokeData dowling$ npm run build

> pokemongo-api@0.0.1 build /Users/dowling/Development/js-seminar/PokeData
> NODE_ENV=production node scripts/build.js

/Users/dowling/Development/js-seminar/PokeData/scripts/build.js:24
        const builder = require(__base + 'app/controllers/filler/' + collectio
        ^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v0.12.4
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! pokemongo-api@0.0.1 build: `NODE_ENV=production node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pokemongo-api@0.0.1 build script 'NODE_ENV=production node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pokemongo-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pokemongo-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pokemongo-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dowling/Development/js-seminar/PokeData/npm-debug.log

```

**Comment by phdowling** [comment]
Note that this was a fresh clone, after running npm install. Is this a bug, or should I be installing differently?

**Comment by phdowling** [comment]
Had to update my node installation, nevermind. Closing.
